// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOLxF_sQgWB3aotXmy9EvQeT6za4j0iYY',
    appId: '1:648966170991:web:0d306aeb78523d9c8e609a',
    messagingSenderId: '648966170991',
    projectId: 'blue-limo-pjt',
    authDomain: 'blue-limo-pjt.firebaseapp.com',
    storageBucket: 'blue-limo-pjt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw6llAvCym9K9Y5wlAN0MAuLl_TxGlvEc',
    appId: '1:648966170991:android:73086c67c0cfbbf28e609a',
    messagingSenderId: '648966170991',
    projectId: 'blue-limo-pjt',
    storageBucket: 'blue-limo-pjt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdfFAAk3yIbvYEdnI8Y12hkLdk7hbDY4w',
    appId: '1:648966170991:ios:2b630844fa1e2c198e609a',
    messagingSenderId: '648966170991',
    projectId: 'blue-limo-pjt',
    storageBucket: 'blue-limo-pjt.appspot.com',
    iosClientId: '648966170991-oofsoajesc2ifj4rf57h1khue8t64nv7.apps.googleusercontent.com',
    iosBundleId: 'com.ssafy.snapstory',
  );
}
