// const rootRoute = '/';
const loginRoute = '/login/';
const registerRoute = '/register/';
const mainRoute = '/main/';
const verifyEmailRoute = '/verify-email/';
const newNoteRoute = '/notes/new-note/';
const iOSRoute = '/ios/';
const androidRoute = '/android/';
const homeRoute = '/home/';
