insert into snapstorydb.quiz_tale_item (quiz_tale_item_id, image_black, image_color, item_eng)
values  (1, 'assets/quizItems/shoe_f', 'assets/quizItems/shoe_t', 'shoe'),
        (2, 'assets/quizItems/crown_f', 'assets/quizItems/crown_t', 'crown'),
        (3, 'assets/quizItems/clock_f', 'assets/quizItems/clock_t', 'clock'),
        (4, 'assets/quizItems/dog_f', 'assets/quizItems/dog_t', 'dog'),
        (5, 'assets/quizItems/apple_f', 'assets/quizItems/apple_t', 'apple'),
        (6, 'assets/quizItems/flower_f', 'assets/quizItems/flower_t', 'flower'),
        (7, 'assets/quizItems/horse_f', 'assets/quizItems/horse_t', 'horse'),
        (8, 'assets/quizItems/sword_f', 'assets/quizItems/sword_t', 'sword'),
        (9, 'assets/quizItems/bird_f', 'assets/quizItems/bird_t', 'bird'),
        (10, 'assets/quizItems/tree_f', 'assets/quizItems/tree_t', 'tree'),
        (11, 'assets/quizItems/snowflake_f', 'assets/quizItems/snowflake_t', 'snowflake'),
        (12, 'assets/quizItems/castle_f', 'assets/quizItems/castle_t', 'castle'),
        (13, 'assets/quizItems/lion_f', 'assets/quizItems/lion_t', 'lion'),
        (14, 'assets/quizItems/rainbow_f', 'assets/quizItems/rainbow_t', 'rainbow'),
        (15, 'assets/quizItems/lollipop_f', 'assets/quizItems/lollipop_t', 'lollipop');